apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: taskboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          # CI pipeline replaces this tag with the ECR image URL + git SHA after build+push
          image: 207137402976.dkr.ecr.eu-west-2.amazonaws.com/plane-app-eks/plane-backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: taskboard-secret
                  key: POSTGRES_PASSWORD
            - name: DATABASE_URL
              value: "postgresql://taskboard:$(POSTGRES_PASSWORD)@postgres:5432/taskboard"
            - name: REDIS_URL
              value: "redis://redis:6379"
            - name: PORT
              value: "8000"
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /api/health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 400m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: taskboard
spec:
  selector:
    app: backend
  ports:
    - port: 8000
      targetPort: 8000
